name: Auto Sync

on:
  push:
    branches:
      - main

  workflow_dispatch: # 允许手动触发

  schedule:
    - cron: "0 */1 * * *"

permissions:
  contents: write

jobs:
  job-on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v5
      # Step 2: 发布至 GitHub
      - name: Update Release
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          python ./build.py
          wget --header="Authorization: token $GIT_TOKEN" $BASE_URL/release.py
          python ./release.py --ver "$(cat ./*/version)" --token "$GIT_TOKEN"

  job-on-schedule:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v5
      # Step 2: 激活 HuggingFace Spaces
      - name: Activate HF Spaces
        run: |
          pip install huggingface_hub
          python ./.github/activate.py --tokens "${{ secrets.HF_TOKENS }}"
      # Step 3: 检查活跃度防 CI 休眠
      - name: Keep GitHub actions active
        run: |
          last_commit_ts=$(git log -1 --format=%ct 2>/dev/null)
          now_ts=$(date +%s)
          diff_days=$(((now_ts - last_commit_ts) / 86400))
          if [ $diff_days -gt 58 ]; then
            git config --global user.name "${{ secrets.GIT_NAME }}"
            git config --global user.email "${{ secrets.GIT_EMAIL }}"
            git commit --allow-empty -m "chore: keep repo active [skip ci]"
            git push origin HEAD:main
          else
            echo "Last activity at $(date -d "@$last_commit_ts" '+%Y-%m-%d %H:%M:%S')"
          fi
