name: Auto Release

on:
  push:
    branches:
      - main

  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  job-on-push:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出当前仓库代码
      - name: Checkout repository
        uses: actions/checkout@v5

      # Step 2: 发布至 GitHub
      - name: Update Release
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          python ./build.py
          python ./.github/release.py --ver "$(cat ./*/version)" --token "$GIT_TOKEN"
